// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanFlow_transport_management.Infrastructure.Database;

#nullable disable

namespace UrbanFlow_transport_management.Migrations
{
    [DbContext(typeof(TransportManagementDbContext))]
    [Migration("20260429081846_migVehicleStatuses")]
    partial class migVehicleStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanFlow_transport_management.Models.RouteType", b =>
                {
                    b.Property<int>("RouteTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteTypeId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteTypeId");

                    b.ToTable("RouteTypes");
                });

            modelBuilder.Entity("UrbanFlow_transport_management.Models.Vehicule", b =>
                {
                    b.Property<int>("VehiculeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculeId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastMaintenance")
                        .HasColumnType("date");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NextMaintenance")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ServiceDebut")
                        .HasColumnType("date");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("VehiculeId");

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("UrbanFlow_transport_management.Models.VehiculePosition", b =>
                {
                    b.Property<int>("VehiculePositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculePositionId"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("integer");

                    b.HasKey("VehiculePositionId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("VehiculePositions");
                });

            modelBuilder.Entity("UrbanFlow_transport_management.Models.Vehicule", b =>
                {
                    b.HasOne("UrbanFlow_transport_management.Models.RouteType", "RouteType")
                        .WithMany("Vehicules")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RouteType");
                });

            modelBuilder.Entity("UrbanFlow_transport_management.Models.VehiculePosition", b =>
                {
                    b.HasOne("UrbanFlow_transport_management.Models.Vehicule", "Vehicule")
                        .WithMany("Positions")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("UrbanFlow_transport_management.Models.RouteType", b =>
                {
                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("UrbanFlow_transport_management.Models.Vehicule", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
