<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>UrbanFlow_transport_management</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>1ea3e770-4152-414c-9ebe-fa92a9152cad</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.1.1" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.13.18" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
    
    <ItemGroup>
        <Protobuf Include="Protos\vehicle.proto" GrpcServices="Server"/>
    </ItemGroup>



    <ItemGroup>
      <Folder Include="Application\" />
      <Folder Include="Domain\" />
      <Folder Include="Infrastructure\" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="API\" />
      <Folder Include="Application\" />
      <Folder Include="Domain\" />
      <Folder Include="Infrastructure\" />
    </ItemGroup>

</Project>
